/**
 * UI text in English. Keep the same key structure as es.js — every screen
 * reads through useStrings(), so a missing key here falls back silently
 * to undefined rather than to Spanish.
 */
export const en = {
  common: {
    cancel: 'Cancel',
    delete: 'Delete',
    noActiveAccount: 'No active account.',
  },
  tabs: {
    dashboard: 'Dashboard',
    settings: 'Settings',
  },
  onboarding: {
    eyebrow: 'NEW CHALLENGE',
    title: 'Set up your account',
    subtitle: 'Define the parameters of your evaluation or funded account',
    presetLabel: 'Choose a starting point',
    presetDisclaimer:
      'Always verify your firm’s current rules — these values are just a starting point.',
    presetStarterLabel: '100k Template',
    nameLabel: 'Account name',
    namePlaceholder: 'E.g. My 100k account',
    accountSizeLabel: 'Account size',
    accountSizePlaceholder: 'E.g. 100,000',
    profitTargetLabel: 'Profit target',
    profitTargetPlaceholder: 'E.g. 6,000',
    maxDrawdownLabel: 'Max drawdown',
    maxDrawdownPlaceholder: 'E.g. 3,000',
    minProfitableDaysLabel: 'Min. profitable days',
    minProfitableDaysPlaceholder: 'E.g. 3',
    drawdownTypeLabel: 'Drawdown type',
    drawdownTypeStatic: 'Static',
    drawdownTypeTrailing: 'Trailing',
    consistencyLabel: 'Consistency rule',
    consistencyNone: 'No rule',
    consistencyWithLimit: 'With limit',
    consistencyPctLabel: 'Max % per day',
    submit: 'Create account',
    hint: 'You can edit all these values later from Settings.',
    presetCustomLabel: 'Custom',
    guideTitle: 'Quick guide',
    guideBody:
      'Choose a preset or define your own parameters. Afterward you can log your trades day by day from the Dashboard, review your history in the Calendar, and check your trading metrics in Analytics.',
    guideDismiss: 'Got it',
  },
  accountStatus: {
    label: 'Account status',
    evaluation: 'Evaluation',
    funded: 'Funded',
    badge: 'FUNDED',
    completedTitle: 'You completed the evaluation!',
    completedBody: 'You meet the profit target, consistency, drawdown and minimum profitable days requirements.',
    upgradeCta: 'Upgrade to Funded Account',
    confirmTitle: 'Upgrade to Funded Account',
    confirmBody: 'The evaluation history will be archived separately and profit/drawdown tracking will restart at zero for the Funded phase. You can still view the archived evaluation here.',
    confirmAction: 'Upgrade',
    archivesLabel: 'Phase history',
    archiveTitleFunded: 'Evaluation phase (funded) ✓',
    archiveTitleFailed: 'Evaluation phase (restarted)',
    archiveBody: '{date} · Final result: {profit} · {count} trades',
  },
  breach: {
    title: 'Max drawdown was breached',
    body: 'This account no longer meets your evaluation rules. What do you want to do?',
    restart: 'Restart evaluation',
    save: 'Keep it as is (don’t ask again)',
    delete: 'Delete account',
  },
  calendar: {
    title: 'Calendar',
    weekdays: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    months: [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December',
    ],
    noTradesForDay: 'No trades on this day',
    dayTotal: 'Day total',
    accountsLabel: 'Account',
    tradeLabel: 'Trade',
    allTimeTitle: 'All Time Summary',
    allTimeNetPnl: 'Total P&L',
    allTimeTrades: 'Total trades',
    allTimeDays: 'Days traded',
    allTimeBestDay: 'Best day',
    allTimeWorstDay: 'Worst day',
    allTimeRange: 'From {from} to {to}',
    emptyState: 'No trades logged yet.',
  },
  analytics: {
    title: 'Analytics',
    accountsLabel: 'Account',
    periodWeek: 'Week',
    periodMonth: 'Month',
    periodYear: 'Year',
    periodAll: 'All',
    drawdownTitle: 'Drawdown Curve',
    viewCalendar: 'View calendar →',
    pnlTitle: 'Profit & Loss',
    totalProfitLabel: 'Total profit',
    totalLossLabel: 'Total loss',
    netPnlLabel: 'Net P&L',
    legendGain: 'Profit',
    legendLoss: 'Loss',
    winRateTitle: 'Win Rate',
    totalTradesLabel: 'Total trades',
    winTradesLabel: 'Winning trades',
    lossTradesLabel: 'Losing trades',
    legendWin: 'Wins',
    legendLossTrades: 'Losses',
    winRateLabel: 'Win Rate',
    profitFactorTitle: 'Profit Factor & Expectancy',
    avgWinLabel: 'Average win',
    avgLossLabel: 'Average loss',
    legendAvgWin: 'Avg. win',
    legendAvgLoss: 'Avg. loss',
    profitFactorLabel: 'Profit Factor',
    expectancyLabel: 'Expectancy',
    emptyState: 'No trades in this period.',
  },
  dashboard: {
    noConsistencyRule: 'No consistency rule set',
    withinLimit: 'Within the {limit}% limit',
    overLimit: 'Exceeds the {limit}% limit',
    totalProfit: 'Total profit',
    targetProgress: 'Progress to goal',
    bestDay: 'Best day',
    drawdownUsed: 'Drawdown used',
    floorLabel: 'Floor: {value}',
    daysOperated: 'Days traded:',
    profitable: 'Profitable:',
    minSuffix: 'min.',
    recentTrades: 'Recent trades',
    registerDay: '+ Log day',
  },
  settings: {
    yourAccounts: 'Your accounts',
    addAccount: 'Add new account',
    editParamsEyebrow: 'EDIT PARAMETERS',
    saveChanges: 'Save changes',
    saved: 'Saved ✓',
    deleteLink: 'Delete this account/challenge',
    deleteConfirmTitle: 'Delete this account/challenge',
    deleteConfirmBody: 'This will delete "{name}" and all its day history. This action cannot be undone.',
    deleteConfirmAction: 'Delete',
  },
  accountSwitcher: {
    title: 'Switch account',
  },
  addDay: {
    title: 'Log day',
    resultLabel: 'Day result',
    gain: 'Profit',
    loss: 'Loss',
    amountLabel: 'Amount',
    dateTimeLabel: 'Date and time',
    applyToAccounts: 'Apply to these accounts',
    submit: 'Save day',
  },
  editTrade: {
    title: 'Edit trade',
    saveChanges: 'Save changes',
    deleteLink: 'Delete this trade',
    deleteConfirmTitle: 'Delete trade',
    deleteConfirmBody: 'This action cannot be undone.',
  },
  generalSettings: {
    title: 'General settings',
    generalSection: 'GENERAL',
    hidePnl: 'Hide P&L for privacy',
    languageSection: 'LANGUAGE',
    languageLabel: 'App language',
    languageSpanish: 'Español',
    languageEnglish: 'English',
    accountSection: 'ACCOUNT',
    googleLogin: 'Sign in with Google',
    signOut: 'Sign out',
    signOutConfirmTitle: 'Sign out',
    signOutConfirmBody: 'Are you sure you want to sign out? Your accounts and trades will stay saved in the cloud.',
    signInError: 'Sign-in could not be completed. Please try again.',
    syncBody: 'Your accounts and trades sync automatically to the cloud.',
    premium: 'Premium subscription',
    premiumActive: 'Premium active ✓',
    exportFeature: 'Export XLS/PDF',
    screenshotsFeature: 'Save trade screenshots',
    restorePurchases: 'Restore purchases',
    restoreSuccess: 'Your purchases were restored successfully.',
    restoreEmpty: 'We couldn’t find any active purchase to restore.',
    restoreError: 'The purchase could not be restored. Please try again.',
    comingSoon: 'Coming soon',
    comingSoonBody: 'This feature isn’t available in this version yet.',
    supportSection: 'SUPPORT',
    contactUs: 'Contact us',
    aboutApp: 'About the app',
    aboutBody: 'Prop Consistency Tracker · version {version}',
  },
  premium: {
    title: 'Go Premium',
    subtitle: 'Unlock all features and support the app’s development',
    featuresHeader: 'Features',
    freeHeader: 'Free',
    premiumHeader: 'Premium',
    featureCalendar: 'P&L calendar',
    featureDrawdown: 'Drawdown curve',
    featureNoAds: 'No ads',
    featureAdvancedAnalytics: 'Advanced analytics (Year/All)',
    featureExport: 'Export XLS and PDF',
    featureMultiAccount: 'Multiple accounts',
    featureScreenshots: 'Save trade screenshots',
    priceLabel: 'Monthly subscription',
    priceFallback: '$4.99',
    perMonth: '/month',
    subscribe: 'Subscribe',
    subscribing: 'Processing...',
    restore: 'Restore purchases',
    legalNote: 'The subscription renews automatically every month. You can cancel anytime from Google Play.',
    purchaseError: 'The purchase could not be completed. Please try again.',
    lockedTitle: 'Premium feature',
    lockedBody: 'This feature requires a Premium subscription.',
    accountLimitTitle: 'Free account limit',
    accountLimitBody: 'The free version allows 1 account. Go Premium to add unlimited accounts.',
  },
};
