/**
 * Textos de UI en español (mercado objetivo inicial V1).
 */
export const es = {
  common: {
    cancel: 'Cancelar',
    delete: 'Eliminar',
    noActiveAccount: 'No hay ninguna cuenta activa.',
  },
  tabs: {
    dashboard: 'Dashboard',
    settings: 'Configuración',
  },
  onboarding: {
    eyebrow: 'NUEVO CHALLENGE',
    title: 'Configura tu cuenta',
    subtitle: 'Define los parámetros de tu evaluación o cuenta fondeada',
    presetLabel: 'Elige un punto de partida',
    presetDisclaimer:
      'Verifica siempre las reglas actuales de tu firm — estos valores son solo un punto de partida.',
    presetStarterLabel: 'Plantilla 100k',
    nameLabel: 'Nombre de la cuenta',
    namePlaceholder: 'Ej. Mi cuenta 100k',
    accountSizeLabel: 'Tamaño de cuenta',
    accountSizePlaceholder: 'Ej. 100,000',
    profitTargetLabel: 'Objetivo de profit',
    profitTargetPlaceholder: 'Ej. 6,000',
    maxDrawdownLabel: 'Drawdown máximo',
    maxDrawdownPlaceholder: 'Ej. 3,000',
    minProfitableDaysLabel: 'Días mín. rentables',
    minProfitableDaysPlaceholder: 'Ej. 3',
    drawdownTypeLabel: 'Tipo de drawdown',
    drawdownTypeStatic: 'Estático',
    drawdownTypeTrailing: 'Trailing',
    consistencyLabel: 'Regla de consistencia',
    consistencyNone: 'Sin regla',
    consistencyWithLimit: 'Con límite',
    consistencyPctLabel: '% máximo por día',
    submit: 'Crear cuenta',
    hint: 'Podrás editar todos estos valores después desde Configuración.',
    presetCustomLabel: 'Personalizado',
    guideTitle: 'Guía rápida',
    guideBody:
      'Elige un preset o define tus propios parámetros. Después podrás registrar tus trades día a día desde el Dashboard, revisar tu historial en el Calendario, y ver tus métricas de trading en Analytics.',
    guideDismiss: 'Entendido',
  },
  accountStatus: {
    label: 'Estado de la cuenta',
    evaluation: 'Evaluación',
    funded: 'Fondeada',
    badge: 'FONDEADA',
    completedTitle: '¡Completaste la evaluación!',
    completedBody: 'Cumples con la meta de profit, consistencia, drawdown y días mínimos rentables.',
    upgradeCta: 'Actualizar a Funded Account',
    confirmTitle: 'Actualizar a Funded Account',
    confirmBody: 'Se archivará el historial de la evaluación por separado y el conteo de ganancia y drawdown empezará en cero para la fase Fondeada. Podrás seguir viendo la evaluación archivada aquí.',
    confirmAction: 'Actualizar',
    archivesLabel: 'Historial de fases',
    archiveTitleFunded: 'Fase de evaluación (fondeada) ✓',
    archiveTitleFailed: 'Fase de evaluación (reiniciada)',
    archiveBody: '{date} · Resultado final: {profit} · {count} trades',
  },
  breach: {
    title: 'Se rompió el drawdown máximo',
    body: 'Esta cuenta ya no cumple las reglas de tu evaluación. ¿Qué quieres hacer?',
    restart: 'Reiniciar prueba',
    save: 'Guardar así (no volver a preguntar)',
    delete: 'Eliminar cuenta',
  },
  calendar: {
    title: 'Calendario',
    weekdays: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    months: [
      'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
      'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
    ],
    noTradesForDay: 'Sin trades este día',
    dayTotal: 'Total del día',
    accountsLabel: 'Cuenta',
    tradeLabel: 'Trade',
    allTimeTitle: 'Resumen histórico (All Time)',
    allTimeNetPnl: 'P&L total',
    allTimeTrades: 'Trades totales',
    allTimeDays: 'Días operados',
    allTimeBestDay: 'Mejor día',
    allTimeWorstDay: 'Peor día',
    allTimeRange: 'Del {from} al {to}',
    emptyState: 'No hay trades registrados todavía.',
  },
  analytics: {
    title: 'Analytics',
    accountsLabel: 'Cuenta',
    periodWeek: 'Semana',
    periodMonth: 'Mes',
    periodYear: 'Año',
    periodAll: 'Todo',
    drawdownTitle: 'Curva de Drawdown',
    viewCalendar: 'Ver calendario →',
    pnlTitle: 'Ganancias y Pérdidas',
    totalProfitLabel: 'Ganancia total',
    totalLossLabel: 'Pérdida total',
    netPnlLabel: 'P&L Neto',
    legendGain: 'Ganancia',
    legendLoss: 'Pérdida',
    winRateTitle: 'Win Rate',
    totalTradesLabel: 'Total de operaciones',
    winTradesLabel: 'Operaciones ganadoras',
    lossTradesLabel: 'Operaciones perdedoras',
    legendWin: 'Ganadoras',
    legendLossTrades: 'Perdedoras',
    winRateLabel: 'Win Rate',
    profitFactorTitle: 'Profit Factor y Expectativa',
    avgWinLabel: 'Ganancia promedio',
    avgLossLabel: 'Pérdida promedio',
    legendAvgWin: 'Gan. promedio',
    legendAvgLoss: 'Pérd. promedio',
    profitFactorLabel: 'Profit Factor',
    expectancyLabel: 'Expectativa',
    emptyState: 'No hay trades en este periodo.',
  },
  dashboard: {
    noConsistencyRule: 'Sin regla de consistencia configurada',
    withinLimit: 'Cumples el límite de {limit}%',
    overLimit: 'Excede el límite de {limit}%',
    totalProfit: 'Ganancia total',
    targetProgress: 'Progreso a meta',
    bestDay: 'Mejor día',
    drawdownUsed: 'Drawdown usado',
    floorLabel: 'Piso: {value}',
    daysOperated: 'Días operados:',
    profitable: 'Rentables:',
    minSuffix: 'mín.',
    recentTrades: 'Últimos trades',
    registerDay: '+ Registrar día',
  },
  settings: {
    yourAccounts: 'Tus cuentas',
    addAccount: 'Agregar cuenta nueva',
    editParamsEyebrow: 'EDITAR PARÁMETROS',
    saveChanges: 'Guardar cambios',
    saved: 'Guardado ✓',
    deleteLink: 'Eliminar esta cuenta/challenge',
    deleteConfirmTitle: 'Eliminar esta cuenta/challenge',
    deleteConfirmBody: 'Se borrará "{name}" y todo su historial de días. Esta acción no se puede deshacer.',
    deleteConfirmAction: 'Eliminar',
  },
  accountSwitcher: {
    title: 'Cambiar de cuenta',
  },
  addDay: {
    title: 'Registrar día',
    resultLabel: 'Resultado del día',
    gain: 'Ganancia',
    loss: 'Pérdida',
    amountLabel: 'Monto',
    dateTimeLabel: 'Fecha y hora',
    applyToAccounts: 'Aplicar a estas cuentas',
    submit: 'Guardar día',
  },
  editTrade: {
    title: 'Editar trade',
    saveChanges: 'Guardar cambios',
    deleteLink: 'Eliminar este trade',
    deleteConfirmTitle: 'Eliminar trade',
    deleteConfirmBody: 'Esta acción no se puede deshacer.',
  },
  generalSettings: {
    title: 'Configuración general',
    generalSection: 'GENERAL',
    hidePnl: 'Ocultar P&L por privacidad',
    languageSection: 'IDIOMA',
    languageLabel: 'Idioma de la app',
    languageSpanish: 'Español',
    languageEnglish: 'English',
    accountSection: 'CUENTA',
    googleLogin: 'Iniciar sesión con Google',
    signOut: 'Cerrar sesión',
    signOutConfirmTitle: 'Cerrar sesión',
    signOutConfirmBody: '¿Seguro que quieres cerrar sesión? Tus cuentas y trades seguirán guardados en la nube.',
    signInError: 'No se pudo completar el inicio de sesión. Intenta de nuevo.',
    syncBody: 'Tus cuentas y trades se sincronizan automáticamente en la nube.',
    premium: 'Suscripción Premium',
    premiumActive: 'Premium activo ✓',
    exportFeature: 'Exportar XLS/PDF',
    screenshotsFeature: 'Guardar capturas de trades',
    restorePurchases: 'Restaurar compras',
    restoreSuccess: 'Tus compras se restauraron correctamente.',
    restoreEmpty: 'No encontramos ninguna compra activa para restaurar.',
    restoreError: 'No se pudo restaurar la compra. Intenta de nuevo.',
    comingSoon: 'Próximamente',
    comingSoonBody: 'Esta función todavía no está disponible en esta versión.',
    supportSection: 'SOPORTE',
    contactUs: 'Contactar',
    aboutApp: 'Acerca de la app',
    aboutBody: 'Prop Consistency Tracker · versión {version}',
  },
  premium: {
    title: 'Hazte Premium',
    subtitle: 'Desbloquea todas las funciones y apoya el desarrollo de la app',
    featuresHeader: 'Funciones',
    freeHeader: 'Free',
    premiumHeader: 'Premium',
    featureCalendar: 'Calendario de P&L',
    featureDrawdown: 'Curva de Drawdown',
    featureNoAds: 'Sin anuncios',
    featureAdvancedAnalytics: 'Analytics avanzado (Año/Todo)',
    featureExport: 'Exportar XLS y PDF',
    featureMultiAccount: 'Múltiples cuentas',
    featureScreenshots: 'Guardar capturas de trades',
    priceLabel: 'Suscripción mensual',
    priceFallback: '$4.99',
    perMonth: '/mes',
    subscribe: 'Suscribirse',
    subscribing: 'Procesando...',
    restore: 'Restaurar compras',
    legalNote: 'La suscripción se renueva automáticamente cada mes. Puedes cancelarla cuando quieras desde Google Play.',
    purchaseError: 'No se pudo completar la compra. Intenta de nuevo.',
    lockedTitle: 'Función Premium',
    lockedBody: 'Esta función requiere una suscripción Premium.',
    accountLimitTitle: 'Límite de cuentas gratis',
    accountLimitBody: 'La versión gratuita permite 1 cuenta. Hazte Premium para agregar cuentas ilimitadas.',
  },
};
