/**
 * Textos de UI centralizados en español (mercado objetivo inicial V1).
 * Mantener todo el copy visible al usuario aquí para poder
 * internacionalizar más adelante sin tocar las pantallas.
 */
export const strings = {
  tabs: {
    dashboard: 'Dashboard',
    settings: 'Configuración',
  },
  onboarding: {
    eyebrow: 'NUEVO CHALLENGE',
    title: 'Configura tu cuenta',
    subtitle: 'Define los parámetros de tu evaluación o cuenta fondeada',
    presetLabel: 'Elige un punto de partida',
    nameLabel: 'Nombre de la cuenta',
    namePlaceholder: 'Ej. Tradeify Select 100k',
    accountSizeLabel: 'Tamaño de cuenta',
    accountSizePlaceholder: 'Ej. 100,000',
    profitTargetLabel: 'Objetivo de profit',
    profitTargetPlaceholder: 'Ej. 6,000',
    maxDrawdownLabel: 'Drawdown máximo',
    maxDrawdownPlaceholder: 'Ej. 3,000',
    minProfitableDaysLabel: 'Días mín. rentables',
    minProfitableDaysPlaceholder: 'Ej. 3',
    drawdownTypeLabel: 'Tipo de drawdown',
    drawdownTypeStatic: 'Estático',
    drawdownTypeTrailing: 'Trailing',
    consistencyLabel: 'Regla de consistencia',
    consistencyNone: 'Sin regla',
    consistencyWithLimit: 'Con límite',
    consistencyPctLabel: '% máximo por día',
    submit: 'Crear cuenta',
    hint: 'Podrás editar todos estos valores después desde Configuración.',
    presetCustomLabel: 'Personalizado',
    guideTitle: 'Guía rápida',
    guideBody:
      'Elige un preset o define tus propios parámetros. Después podrás registrar tus trades día a día desde el Dashboard, revisar tu historial en el Calendario, y ver tus métricas de trading en Analytics.',
    guideDismiss: 'Entendido',
  },
  accountStatus: {
    label: 'Estado de la cuenta',
    evaluation: 'Evaluación',
    funded: 'Fondeada',
    badge: 'FONDEADA',
    completedTitle: '¡Completaste la evaluación!',
    completedBody: 'Cumples con la meta de profit, consistencia, drawdown y días mínimos rentables.',
    upgradeCta: 'Actualizar a Funded Account',
    confirmTitle: 'Actualizar a Funded Account',
    confirmBody: 'Se archivará el historial de la evaluación por separado y el conteo de ganancia y drawdown empezará en cero para la fase Fondeada. Podrás seguir viendo la evaluación archivada aquí.',
    confirmAction: 'Actualizar',
    archivesLabel: 'Historial de fases',
    archiveTitleFunded: 'Fase de evaluación (fondeada) ✓',
    archiveTitleFailed: 'Fase de evaluación (reiniciada)',
    archiveBody: '{date} · Resultado final: {profit} · {count} trades',
  },
  breach: {
    title: 'Se rompió el drawdown máximo',
    body: 'Esta cuenta ya no cumple las reglas de tu evaluación. ¿Qué quieres hacer?',
    restart: 'Reiniciar prueba',
    save: 'Guardar así (no volver a preguntar)',
    delete: 'Eliminar cuenta',
  },
  calendar: {
    title: 'Calendario',
    weekdays: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    months: [
      'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
      'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
    ],
    noTradesForDay: 'Sin trades este día',
    dayTotal: 'Total del día',
    accountsLabel: 'Cuenta',
    allTimeTitle: 'Resumen histórico (All Time)',
    allTimeNetPnl: 'P&L total',
    allTimeTrades: 'Trades totales',
    allTimeDays: 'Días operados',
    allTimeBestDay: 'Mejor día',
    allTimeWorstDay: 'Peor día',
    allTimeRange: 'Del {from} al {to}',
    emptyState: 'No hay trades registrados todavía.',
  },
  analytics: {
    title: 'Analytics',
    accountsLabel: 'Cuenta',
    periodWeek: 'Semana',
    periodMonth: 'Mes',
    periodYear: 'Año',
    periodAll: 'Todo',
    drawdownTitle: 'Curva de Drawdown',
    viewCalendar: 'Ver calendario →',
    pnlTitle: 'Ganancias y Pérdidas',
    totalProfitLabel: 'Ganancia total',
    totalLossLabel: 'Pérdida total',
    netPnlLabel: 'P&L Neto',
    legendGain: 'Ganancia',
    legendLoss: 'Pérdida',
    winRateTitle: 'Win Rate',
    totalTradesLabel: 'Total de operaciones',
    winTradesLabel: 'Operaciones ganadoras',
    lossTradesLabel: 'Operaciones perdedoras',
    legendWin: 'Ganadoras',
    legendLossTrades: 'Perdedoras',
    winRateLabel: 'Win Rate',
    profitFactorTitle: 'Profit Factor y Expectativa',
    avgWinLabel: 'Ganancia promedio',
    avgLossLabel: 'Pérdida promedio',
    legendAvgWin: 'Gan. promedio',
    legendAvgLoss: 'Pérd. promedio',
    profitFactorLabel: 'Profit Factor',
    expectancyLabel: 'Expectativa',
    emptyState: 'No hay trades en este periodo.',
  },
  generalSettings: {
    title: 'Configuración general',
    generalSection: 'GENERAL',
    hidePnl: 'Ocultar P&L por privacidad',
    accountSection: 'CUENTA',
    googleLogin: 'Iniciar sesión con Google',
    premium: 'Suscripción Premium',
    comingSoon: 'Próximamente',
    comingSoonBody: 'Esta función todavía no está disponible en esta versión.',
    supportSection: 'SOPORTE',
    contactUs: 'Contactar',
    aboutApp: 'Acerca de la app',
    aboutBody: 'Prop Consistency Tracker · versión {version}',
  },
};
